data:
  path1: "./data/raw/weather.db"
  path2: "./data/raw/air_quality.db"

target_feature: 'Daily Solar Panel Efficiency'

models:
  logistic_regression:
    enabled: True
    params:
      max_iter: 100
      C : 1.0

  xgboost:
    enabled: True
    params:
      n_estimators: [50, 100, 200, 500]
      learning_rate: [0.001, 0.005, 0.01, 0.05]
      max_depth: [3, 6 ,9]
    cv: 5

  autogluon:
    enabled: True
    params:
      time_limit: 3600
      hyperparameters: 'multimodal'
      num_stack_levels: 1
      num_bag_folds: 5
      presets: 'best_quality'


seed: 1 